In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\DELL\Downloads\10-K.csv")
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2023,"211,915,000,000","72,361,000,000","411,976,000,000","205,753,000,000","87,582,000,000"
1,Microsoft,2022,"198,270,000,000","72,738,000,000","364,840,000,000","198,298,000,000","89,035,000,000"
2,Microsoft,2021,"168,088,000,000","61,271,000,000","333,779,000,000","191,791,000,000","76,740,000,000"
3,Tesla,2023,"96,773,000,000","14,974,000,000","106,618,000,000","43,009,000,000","13,256,000,000"
4,Tesla,2022,"81,462,000,000","12,587,000,000","82,338,000,000","36,440,000,000","14,724,000,000"
5,Tesla,2021,"53,823,000,000","5,644,000,000","62,131,000,000","30,548,000,000","11,497,000,000"
6,Apple,2023,"383,285,000,000","96,995,000,000","352,583,000,000","290,437,000,000","110,543,000,000"
7,Apple,2022,"394,328,000,000","99,803,000,000","352,755,000,000","302,083,000,000","122,151,000,000"
8,Apple,2021,"365,817,000,000","94,680,000,000","351,022,000,000","287,912,000,000","104,038,000,000"

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            9 non-null      object
 1   Year               9 non-null      int64
 2   Total Revenue      9 non-null      object
 3   Net Income         9 non-null      object
 4   Total Assets       9 non-null      object
 5   Total Liabilities  9 non-null      object
 6   Cash Flow          9 non-null      object
dtypes: int64(1), object(6)
memory usage: 636.0+ bytes

In [6]:
def remove_commas(value):
    value= value.split(',')
    value = ''.join(value)
    return int(value)

In [7]:
for col in df.columns:
    if col not in ["Company", "Year"]:
        df[col] = df[col].map(remove_commas)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company            9 non-null      object
 1   Year               9 non-null      int64
 2   Total Revenue      9 non-null      int64
 3   Net Income         9 non-null      int64
 4   Total Assets       9 non-null      int64
 5   Total Liabilities  9 non-null      int64
 6   Cash Flow          9 non-null      int64
dtypes: int64(6), object(1)
memory usage: 636.0+ bytes

In [9]:
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
0,Microsoft,2023,211915000000,72361000000,411976000000,205753000000,87582000000
1,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000
2,Microsoft,2021,168088000000,61271000000,333779000000,191791000000,76740000000
3,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000
4,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000
5,Tesla,2021,53823000000,5644000000,62131000000,30548000000,11497000000
6,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000
7,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000
8,Apple,2021,365817000000,94680000000,351022000000,287912000000,104038000000

In [10]:
df= df.sort_values(['Company', 'Year'], ascending=True). groupby('Company').head()
df

,Company,Year,Total Revenue,Net Income,Total Assets,Total Liabilities,Cash Flow
8,Apple,2021,365817000000,94680000000,351022000000,287912000000,104038000000
7,Apple,2022,394328000000,99803000000,352755000000,302083000000,122151000000
6,Apple,2023,383285000000,96995000000,352583000000,290437000000,110543000000
2,Microsoft,2021,168088000000,61271000000,333779000000,191791000000,76740000000
1,Microsoft,2022,198270000000,72738000000,364840000000,198298000000,89035000000
0,Microsoft,2023,211915000000,72361000000,411976000000,205753000000,87582000000
5,Tesla,2021,53823000000,5644000000,62131000000,30548000000,11497000000
4,Tesla,2022,81462000000,12587000000,82338000000,36440000000,14724000000
3,Tesla,2023,96773000000,14974000000,106618000000,43009000000,13256000000

In [11]:
df_revenue = pd.DataFrame(columns=['Company', 'Year', 'Total Revenue', 'Revenue Growth (%)'])
df_revenue['Company'] = df['Company']
df_revenue['Year'] = df['Year']
df_revenue['Total Revenue'] = df['Total Revenue']
df_revenue['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue'].pct_change()* 100
df_revenue

     Company  Year  Total Revenue  Revenue Growth (%)
8      Apple  2021   365817000000                 NaN
7      Apple  2022   394328000000            7.793788
6      Apple  2023   383285000000           -2.800461
2  Microsoft  2021   168088000000                 NaN
1  Microsoft  2022   198270000000           17.956071
0  Microsoft  2023   211915000000            6.882030
5      Tesla  2021    53823000000                 NaN
4      Tesla  2022    81462000000           51.351653
3      Tesla  2023    96773000000           18.795267

All the three companies (Apple, Microsoft and Tesla) saw an increase in total revenue from the year 2021 to 2022.
the growth of revenue slowed down for Microsoft and Tesla in the year 2023 while Apple a saw decrease in revenue for 2023.

In [12]:
df_income = pd.DataFrame(columns=['company', 'year', 'Net Income', 'Net Income Growth (%)'])
df_income['Company'] = df['Company']
df_income['Year'] =df['Year']
df_income['Net Income'] =df['Net Income']
df_income['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income'].pct_change() * 100
df_income

  company year   Net Income  Net Income Growth (%)    Company  Year
8     NaN  NaN  94680000000                    NaN      Apple  2021
7     NaN  NaN  99803000000               5.410858      Apple  2022
6     NaN  NaN  96995000000              -2.813543      Apple  2023
2     NaN  NaN  61271000000                    NaN  Microsoft  2021
1     NaN  NaN  72738000000              18.715216  Microsoft  2022
0     NaN  NaN  72361000000              -0.518299  Microsoft  2023
5     NaN  NaN   5644000000                    NaN      Tesla  2021
4     NaN  NaN  12587000000             123.015592      Tesla  2022
3     NaN  NaN  14974000000              18.964010      Tesla  2023

 All the three companies (Apple, Microsoft and tesla) saw an increase in net income from the year 2021 to 2022. Meanwhile
the net income decreased for Apple and Microsoft in the year 2023 while tesla saw an increase in net income.

In [13]:
df_assets = pd.DataFrame(columns=['company', 'year', 'Total Assets', 'Total Assets Growth (%)'])
df_assets['Company'] = df['Company']
df_assets['Year'] =df['Year']
df_assets['Total Assets'] =df['Total Assets']
df_assets['Total Assets Growth (%)'] = df.groupby(['Company'])['Total Assets'].pct_change() * 100
df_assets

  company year  Total Assets  Total Assets Growth (%)    Company  Year
8     NaN  NaN  351022000000                      NaN      Apple  2021
7     NaN  NaN  352755000000                 0.493701      Apple  2022
6     NaN  NaN  352583000000                -0.048759      Apple  2023
2     NaN  NaN  333779000000                      NaN  Microsoft  2021
1     NaN  NaN  364840000000                 9.305858  Microsoft  2022
0     NaN  NaN  411976000000                12.919636  Microsoft  2023
5     NaN  NaN   62131000000                      NaN      Tesla  2021
4     NaN  NaN   82338000000                32.523217      Tesla  2022
3     NaN  NaN  106618000000                29.488207      Tesla  2023

 All the three companies (Apple, Microsoft and tesla) saw an increase in total assets from the year 2021 to 2022 with
Apple having very minimal growth of -0.5%. the growth of total assets slowed down for Tesla in th year 2023 while it 
continued to increase for Microsoft.Meanwhile Apple saw a very slight decrease in total assets for 2023.

In [14]:
df_liability = pd.DataFrame(columns=['company', 'year', 'Total Liabilities', 'Total Liabilities Growth (%)'])
df_liability['Company'] = df['Company']
df_liability['Year'] =df['Year']
df_liability['Total Liabilities'] =df['Total Liabilities']

df_liability['Total Liabilities Growth (%)'] = df.groupby(['Company'])['Total Liabilities'].pct_change() * 100
df_liability

,company,year,Total Liabilities,Total Liabilities Growth (%),Company,Year
8,NaN,NaN,287912000000,NaN,Apple,2021
7,NaN,NaN,302083000000,4.921990,Apple,2022
6,NaN,NaN,290437000000,-3.855232,Apple,2023
2,NaN,NaN,191791000000,NaN,Microsoft,2021
1,NaN,NaN,198298000000,3.392756,Microsoft,2022
0,NaN,NaN,205753000000,3.759493,Microsoft,2023
5,NaN,NaN,30548000000,NaN,Tesla,2021
4,NaN,NaN,36440000000,19.287678,Tesla,2022
3,NaN,NaN,43009000000,18.026894,Tesla,2023

In [15]:
df_cashflow = pd.DataFrame(columns=['Company', 'Year', 'Cash Flow', 'Cash Flow Growth (%)'])
df_cashflow['Company'] = df['Company']
df_cashflow['Year'] =df['Year']

df_cashflow['Cash Flow'] =df['Cash Flow']

df_cashflow['Cash Flow Growth (%)'] = df.groupby(['Company'])['Cash Flow'].pct_change() * 100
df_cashflow

     Company  Year     Cash Flow  Cash Flow Growth (%)
8      Apple  2021  104038000000                   NaN
7      Apple  2022  122151000000             17.409985
6      Apple  2023  110543000000             -9.502992
2  Microsoft  2021   76740000000                   NaN
1  Microsoft  2022   89035000000             16.021631
0  Microsoft  2023   87582000000             -1.631942
5      Tesla  2021   11497000000                   NaN
4      Tesla  2022   14724000000             28.068192
3      Tesla  2023   13256000000             -9.970117

All the three companies(Apple, Microsoft and Tesla) saw an increase in operations cash flow from the year 2021 to 2022.
the  cash flow decreased for all the three companies in the year 2023 with microsoft having the least decrease in cash flow value.

In [18]:
df.to_csv("Report.csv", index = False)